import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

type Event = {event:string; callsign:string; timestamp:string};
type RfValue = boolean|number|boolean[]|number[]|null;
type RfEvent = {kind:'tx'|'rx';state:boolean|boolean[]|null;sql_open?:boolean|boolean[];active?:boolean|boolean[];siglev?:number|number[];timestamp?:string};
type Status = {node:Record<string, string|number>; svxlink:{status:string;pid:number|null;substate:string}; reflector:{events:Event[];count:number;last_heard:Event|null;available:boolean}; rf:{available:boolean;tx:RfEvent|null;rx:RfEvent|null;reason:string}; events:{enabled:boolean;available:boolean;reason:string}; config:Record<string,Record<string,string>>; demo:boolean; updated_at:string};
const api='/api';
const value=(obj:Record<string, unknown>, ...keys:string[]) => keys.map(k=>obj[k]).find(v=>v !== undefined && v !== null && v !== '') as string|number|undefined;
function Card({title,value:content,detail,active=false}:{title:string;value:string;detail?:string;active?:boolean}) { return <article className={'card '+(active?'active':'')}><small>{title}</small><strong>{content}</strong>{detail&&<span>{detail}</span>}</article>; }
function App() {
  const [s,setS]=useState<Status|null>(null); const [tg,setTg]=useState<{active:string|null;confirmed:boolean;external:{available:boolean;source?:string;active?:{call:string;tg:string}|null;client_count?:number|null;live?:{call:string;tg:string;server?:string;time?:string}[];last_heard?:{call:string;tg:string}[];reason:string};control:{enabled:boolean;reason:string}}|null>(null); const [err,setErr]=useState('');
  useEffect(()=>{const load=()=>Promise.all([fetch(api+'/status'),fetch(api+'/talkgroups')]).then(async ([status,talkgroups])=>{if(!status.ok||!talkgroups.ok) throw Error(); return [await status.json(),await talkgroups.json()] as const;}).then(([status,talkgroups])=>{setS(status);setTg(talkgroups);}).catch(()=>setErr('Backend nicht erreichbar.')); load(); const timer=setInterval(load,15000); return()=>clearInterval(timer);},[]);
  if(err)return <main><h1>{err}</h1></main>; if(!s||!tg)return <main><p>Lade Live-Status …</p></main>;
  const n=s.node; const name=String(value(n,'Callsign','CALLSIGN','nodeLocation','Location')||'SvxLink Node'); const freq=value(n,'TXFREQ','RXFREQ')||'nicht verfügbar'; const logics=Object.values(s.config).map(c=>c.LOGICS).filter(Boolean).join(', ')||'nicht konfiguriert'; const last=s.reflector.last_heard; const external=tg.external; const externalActive=external.active; const activeNetwork=external.live||[]; const rf=s.rf; const hasActive=(state:RfEvent['state'])=>Array.isArray(state)?state.some(Boolean):state===true; const rfValue=(event:RfEvent|null,label:string)=>!rf.available?'nicht verfügbar':hasActive(event?.state ?? null)?`${label} aktiv`:`${label} inaktiv`; const renderRf=(field:RfValue|undefined)=>Array.isArray(field)?`[${field.join(', ')}]`:field; const rfDetail=(event:RfEvent|null)=>event?[event?.sql_open!==undefined?`SQL ${renderRf(event.sql_open)}`:'',event?.active!==undefined?`Active ${renderRf(event.active)}`:'',event.siglev!==undefined?`Siglev ${renderRf(event.siglev)}`:'',event.timestamp||''].filter(Boolean).join(' · '):rf.reason;
  return <><header><div><small>SVXLINK · FM-FUNKNETZ</small><h1>{name}</h1><p>{value(n,'Location','nodeLocation')||'Standort nicht konfiguriert'} · {freq} MHz</p></div><b className="badge">{s.demo?'DEMO':'LIVE'}</b></header><main>
    <section className="hero"><div><small>SVXLINK-SERVICE</small><h2>{s.svxlink.status==='online'?'Online':'Nicht verfügbar'}</h2><p>{s.svxlink.status==='online'?`Dienst läuft · PID ${s.svxlink.pid||'—'} · ${s.svxlink.substate}`:'Dienststatus konnte nicht ermittelt werden'}</p></div></section>
    <section className="section-block"><div className="section-heading"><h3>Lokale RF-Aktivität</h3><small>Nur read-only STATE_PTY</small></div><div className="grid"><Card title="SHARI TX / PTT" value={rfValue(rf.tx,'TX/PTT')} detail={rfDetail(rf.tx)} active={hasActive(rf.tx?.state ?? null)}/><Card title="SHARI RX / Squelch" value={rfValue(rf.rx,'RX')} detail={rfDetail(rf.rx)} active={hasActive(rf.rx?.state ?? null)}/><Card title="Lokale TG / Talker / EchoLink" value="unavailable" detail={s.events.enabled?s.events.reason:'Kein lokaler Event-Emitter aktiviert.'}/></div></section>
    <section className="section-block"><div className="section-heading"><h3>FM-Funknetz-Aktivität</h3><small>Klar getrennte externe Live-Quelle</small></div><div className="grid"><Card title="Aktive TG" value={externalActive?`TG ${externalActive.tg}`:'nicht verfügbar'} detail={externalActive?`${externalActive.call} · externe FM-Funknetz-Quelle`:external.reason} active={external.available}/><Card title="Clientzahl" value={String(external.client_count ?? 'nicht verfügbar')} detail="Öffentlicher Live-Feed liefert keine verlässliche Clientzahl"/><Card title="Aktive Talker/TGs" value={`${activeNetwork.length} Einträge`} detail="Vollständige aktuelle Feed-Liste (begrenzt auf 100)"/></div><div className="feed-list">{activeNetwork.map((entry,i)=><div className="event" key={`${entry.call}-${entry.tg}-${i}`}><b>{entry.call||'unknown'}</b><span>TG {entry.tg||'unknown'}{entry.server?` · ${entry.server}`:''}</span><time>{entry.time||'—'}</time></div>)}{!activeNetwork.length&&<p>{external.reason||'Keine externen Live-Einträge.'}</p>}</div></section>
    <section className="grid"><Card title="Station / Standort" value={name} detail={String(value(n,'Locator','LAT')||'Koordinaten nicht verfügbar')}/><Card title="Frequenz" value={`${freq} MHz`} detail={`RX ${value(n,'RXFREQ')||'—'} · Mode ${value(n,'Mode')||'—'}`}/><Card title="Aktive TG (lokal bestätigt)" value={tg.active||'nicht bestätigt'} detail={tg.confirmed?'Neue ReflectorLogic-Logzeile':'Keine korrelierte Auswahl'} active={tg.confirmed}/><Card title="TG-Steuerung" value={tg.control.enabled?'aktiviert':'deaktiviert'} detail={tg.control.reason}/><Card title="Reflector-Aktivität" value={`${s.reflector.count} Ereignisse`} detail={s.reflector.available?'Aus lokalen SvxLink-Logs':'Logquelle nicht verfügbar'} active={s.reflector.count>0}/><Card title="Last Heard" value={last?`${last.callsign} · ${last.event}`:'Keine Ereignisse'} detail={last?.timestamp||'—'}/><Card title="Logics / NetLink" value={logics} detail="Allowlisted Konfiguration"/></section>
    <section className="events"><div className="section-heading"><h3>Letzte Reflector-Ereignisse</h3><small>Aktualisiert {new Date(s.updated_at).toLocaleTimeString('de-DE')}</small></div>{s.reflector.events.slice(-8).reverse().map((e,i)=><div className="event" key={`${e.timestamp}-${i}`}><b>{e.callsign}</b><span>{e.event==='joined'?'beigetreten':'verlassen'}</span><time>{e.timestamp}</time></div>)}{!s.reflector.events.length&&<p>Keine lokalen Join/Leave-Ereignisse im verfügbaren Log.</p>}</section>
  </main><nav>Read-only · Keine Steuerbefehle · Keine Secrets</nav></>;
}
createRoot(document.getElementById('root')!).render(<App/>);
